"""Newsletter added

Revision ID: 235a5e3ce81b
Revises: 6c1e441caa77
Create Date: 2024-02-12 20:55:12.137030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '235a5e3ce81b'
down_revision = '6c1e441caa77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NewNewsletter', schema=None) as batch_op:
        batch_op.drop_index('Letter')
        batch_op.drop_index('LetterHeader')

    op.drop_table('NewNewsletter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NewNewsletter',
    sa.Column('LetterID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('LetterHeader', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Letter', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('LetterID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('NewNewsletter', schema=None) as batch_op:
        batch_op.create_index('LetterHeader', ['LetterHeader'], unique=True)
        batch_op.create_index('Letter', ['Letter'], unique=True)

    # ### end Alembic commands ###
