"""Initial migration.

Revision ID: 6c1e441caa77
Revises:
Create Date: 2024-02-12 16:18:55.075888

"""

from alembic import op
import sqlalchemy as sa
import flask_security.datastore


# revision identifiers, used by Alembic.
revision = "6c1e441caa77"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Categories",
        sa.Column("CategoryID", sa.Integer(), nullable=False),
        sa.Column("CategoryName", sa.String(length=80), nullable=False),
        sa.Column("Description", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("CategoryID"),
    )
    op.create_table(
        "NewsletterEmails",
        sa.Column("EmailID", sa.Integer(), nullable=False),
        sa.Column("Email", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("EmailID"),
        sa.UniqueConstraint("Email"),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("permissions", flask_security.datastore.AsaList(), nullable=True),
        sa.Column(
            "update_datetime",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("fs_webauthn_user_handle", sa.String(length=64), nullable=True),
        sa.Column(
            "mf_recovery_codes", flask_security.datastore.AsaList(), nullable=True
        ),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("us_phone_number", sa.String(length=128), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("us_totp_secrets", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("fs_uniquifier", sa.String(length=64), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("current_login_at", sa.DateTime(), nullable=True),
        sa.Column("last_login_ip", sa.String(length=64), nullable=True),
        sa.Column("current_login_ip", sa.String(length=64), nullable=True),
        sa.Column("login_count", sa.Integer(), nullable=True),
        sa.Column("tf_primary_method", sa.String(length=64), nullable=True),
        sa.Column("tf_totp_secret", sa.String(length=255), nullable=True),
        sa.Column("tf_phone_number", sa.String(length=128), nullable=True),
        sa.Column(
            "create_datetime",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_datetime",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("fs_uniquifier"),
        sa.UniqueConstraint("fs_webauthn_user_handle"),
        sa.UniqueConstraint("us_phone_number"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "Products",
        sa.Column("ProductID", sa.Integer(), nullable=False),
        sa.Column("ProductName", sa.String(length=40), nullable=False),
        sa.Column("SupplierID", sa.Integer(), nullable=False),
        sa.Column("CategoryId", sa.Integer(), nullable=False),
        sa.Column("QuantityPerUnit", sa.String(length=20), nullable=False),
        sa.Column("UnitPrice", sa.Float(), nullable=False),
        sa.Column("UnitsInStock", sa.Integer(), nullable=False),
        sa.Column("UnitsOnOrder", sa.Integer(), nullable=False),
        sa.Column("ReorderLevel", sa.Integer(), nullable=False),
        sa.Column("Discontinued", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["CategoryId"],
            ["Categories.CategoryID"],
        ),
        sa.PrimaryKeyConstraint("ProductID"),
    )
    op.create_table(
        "roles_users",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roles_users")
    op.drop_table("Products")
    op.drop_table("user")
    op.drop_table("role")
    op.drop_table("NewsletterEmails")
    op.drop_table("Categories")
    # ### end Alembic commands ###
