"""Newsletter update

Revision ID: e9df6cb34345
Revises: 235a5e3ce81b
Create Date: 2024-02-12 22:58:08.661268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9df6cb34345'
down_revision = '235a5e3ce81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Newsletter', schema=None) as batch_op:
        batch_op.drop_index('Content')
        batch_op.drop_index('Subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Newsletter', schema=None) as batch_op:
        batch_op.create_index('Subject', ['Subject'], unique=True)
        batch_op.create_index('Content', ['Content'], unique=True)

    # ### end Alembic commands ###
